"""HTML report output — visual report with severity breakdown."""

from __future__ import annotations

from nerve.models.scan import ScanResult

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nerve AI Security Audit Report</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0a; color: #e0e0e0; }}
  .container {{ max-width: 1200px; margin: 0 auto; padding: 2rem; }}
  h1 {{ color: #8b5cf6; font-size: 2rem; margin-bottom: 0.5rem; }}
  h2 {{ color: #a78bfa; font-size: 1.4rem; margin: 2rem 0 1rem; border-bottom: 1px solid #333; padding-bottom: 0.5rem; }}
  h3 {{ color: #c4b5fd; font-size: 1.1rem; margin: 1rem 0 0.5rem; }}
  .header {{ border-bottom: 2px solid #8b5cf6; padding-bottom: 1rem; margin-bottom: 2rem; }}
  .meta {{ color: #888; font-size: 0.9rem; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
  .stat {{ background: #1a1a2e; border-radius: 8px; padding: 1rem; text-align: center; }}
  .stat-value {{ font-size: 2rem; font-weight: bold; }}
  .stat-label {{ color: #888; font-size: 0.85rem; margin-top: 0.3rem; }}
  .critical {{ color: #ef4444; }}
  .high {{ color: #f97316; }}
  .medium {{ color: #eab308; }}
  .low {{ color: #22c55e; }}
  .info {{ color: #3b82f6; }}
  .risk {{ color: #8b5cf6; }}
  .finding {{ background: #1a1a2e; border-radius: 8px; padding: 1.5rem; margin: 1rem 0; border-left: 4px solid; }}
  .finding.severity-critical {{ border-color: #ef4444; }}
  .finding.severity-high {{ border-color: #f97316; }}
  .finding.severity-medium {{ border-color: #eab308; }}
  .finding.severity-low {{ border-color: #22c55e; }}
  .finding.severity-info {{ border-color: #3b82f6; }}
  .finding-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }}
  .finding-title {{ font-weight: bold; font-size: 1.05rem; }}
  .badge {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: bold; text-transform: uppercase; }}
  .badge-critical {{ background: #ef4444; color: white; }}
  .badge-high {{ background: #f97316; color: white; }}
  .badge-medium {{ background: #eab308; color: black; }}
  .badge-low {{ background: #22c55e; color: white; }}
  .badge-info {{ background: #3b82f6; color: white; }}
  .finding-meta {{ display: flex; gap: 1rem; color: #888; font-size: 0.85rem; margin: 0.5rem 0; }}
  .evidence {{ background: #111; border-radius: 4px; padding: 0.75rem; margin: 0.5rem 0; font-family: monospace; font-size: 0.85rem; white-space: pre-wrap; overflow-x: auto; max-height: 300px; }}
  .remediation {{ background: #0f2e0f; border-radius: 4px; padding: 0.75rem; margin: 0.5rem 0; color: #4ade80; }}
  .chain {{ background: #1a1a2e; border-radius: 8px; padding: 1.5rem; margin: 1rem 0; border-left: 4px solid #8b5cf6; }}
  .chain-title {{ font-weight: bold; color: #8b5cf6; font-size: 1.1rem; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #333; color: #666; font-size: 0.8rem; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Nerve AI Security Audit</h1>
    <p class="meta">Target: {target} | Scan ID: {scan_id} | Duration: {duration:.1f}s</p>
    <p class="meta">Started: {started} | Agents: {agents}</p>
  </div>

  <div class="stats">
    <div class="stat"><div class="stat-value risk">{risk_score:.0f}</div><div class="stat-label">Risk Score</div></div>
    <div class="stat"><div class="stat-value critical">{critical}</div><div class="stat-label">Critical</div></div>
    <div class="stat"><div class="stat-value high">{high}</div><div class="stat-label">High</div></div>
    <div class="stat"><div class="stat-value medium">{medium}</div><div class="stat-label">Medium</div></div>
    <div class="stat"><div class="stat-value low">{low}</div><div class="stat-label">Low</div></div>
    <div class="stat"><div class="stat-value info">{info_count}</div><div class="stat-label">Info</div></div>
    <div class="stat"><div class="stat-value" style="color:#8b5cf6">{chains}</div><div class="stat-label">Kill Chains</div></div>
  </div>

  {kill_chains_html}

  <h2>Findings ({total_findings})</h2>
  {findings_html}

  <div class="footer">
    Generated by Nerve v{version} — AI-powered security auditor for AI systems<br>
    github.com/BreachLine/nerve
  </div>
</div>
</body>
</html>"""


def render_html(result: ScanResult) -> str:
    # Sort findings by severity (critical first)
    from nerve import __version__
    from nerve.models.finding import SEVERITY_ORDER
    sorted_findings = sorted(result.findings, key=lambda f: SEVERITY_ORDER[f.severity], reverse=True)

    findings_parts: list[str] = []
    for f in sorted_findings:
        evidence_html = ""
        if f.evidence.payload:
            evidence_html += f'<div class="evidence">Payload: {_escape(f.evidence.payload)}</div>'
        if f.evidence.request:
            evidence_html += f'<div class="evidence">Request: {_escape(f.evidence.request[:500])}</div>'
        if f.evidence.response:
            evidence_html += f'<div class="evidence">Response: {_escape(f.evidence.response[:500])}</div>'

        remediation_html = ""
        if f.remediation:
            remediation_html = f'<div class="remediation">{_escape(f.remediation)}</div>'

        tags = " | ".join(t for t in [f.owasp_llm, f.owasp_mcp, f.mitre_atlas, f.cwe] if t)

        findings_parts.append(f"""
  <div class="finding severity-{f.severity.value}">
    <div class="finding-header">
      <span class="finding-title">{_escape(f.title)}</span>
      <span class="badge badge-{f.severity.value}">{f.severity.value}</span>
    </div>
    <div class="finding-meta">
      <span>Agent: {f.agent}</span>
      <span>Target: {_escape(f.target)}</span>
      <span>CVSS: {f.cvss}</span>
      <span>Confidence: {f.confidence:.0%}</span>
      {f'<span>{tags}</span>' if tags else ''}
    </div>
    <p>{_escape(f.description)}</p>
    {evidence_html}
    {remediation_html}
  </div>""")

    chains_parts: list[str] = []
    if result.kill_chains:
        chains_parts.append("<h2>Kill Chains</h2>")
        for chain in result.kill_chains:
            chains_parts.append(f"""
  <div class="chain">
    <div class="chain-title">{_escape(chain.title)}</div>
    <p>{_escape(chain.description)}</p>
    <p class="meta">CVSS: {chain.total_cvss} | Steps: {len(chain.findings)}</p>
  </div>""")

    return _HTML_TEMPLATE.format(
        target=_escape(result.target),
        scan_id=result.scan_id,
        duration=result.duration_seconds,
        started=result.started_at.strftime("%Y-%m-%d %H:%M:%S UTC"),
        agents=", ".join(result.agents_run),
        risk_score=result.risk_score,
        critical=result.critical_count,
        high=result.high_count,
        medium=result.medium_count,
        low=result.low_count,
        info_count=result.info_count,
        chains=len(result.kill_chains),
        total_findings=len(result.findings),
        kill_chains_html="\n".join(chains_parts),
        findings_html="\n".join(findings_parts),
        version=__version__,
    )


def _escape(text: str) -> str:
    """HTML-escape text to prevent XSS in reports."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#x27;")
    )
